In [5]:
import pandas as pd
import numpy as np

In [6]:
# Load the dataset
DataSet = pd.read_csv(r"C:\Users\th2\Documents\Ai.Ml_4pm\Online Store.csv") 
#DataSet

           Date     Product Region CustomerID  Quantity   Sales  Revenue
0    2025-02-16     Printer   East   CUST0065         8  146.77  1174.16
1    2025-03-28     Monitor  South   CUST0032         3  587.17  1761.51
2    2025-03-27    Keyboard   East   CUST0034         2  738.15  1476.30
3    2025-01-02     Printer   West   CUST0092         1  883.87   883.87
4    2025-01-17      Tablet  North   CUST0095         3  742.68  2228.04
..          ...         ...    ...        ...       ...     ...      ...
500  2025-03-23  Smartphone  South   CUST0007         8  698.42  5587.36
501  2025-03-08      Tablet  South   CUST0074         4  656.06  2624.24
502  2025-02-26     Printer  South   CUST0052         8  472.72  3781.76
503  2025-02-02      Laptop   West   CUST0079         1  104.45   104.45
504  2025-03-30    Keyboard  North   CUST0054         3  722.95  2168.85

[505 rows x 7 columns]

In [7]:
# Preview the first few rows
DataSet.head()

         Date   Product Region CustomerID  Quantity   Sales  Revenue
0  2025-02-16   Printer   East   CUST0065         8  146.77  1174.16
1  2025-03-28   Monitor  South   CUST0032         3  587.17  1761.51
2  2025-03-27  Keyboard   East   CUST0034         2  738.15  1476.30
3  2025-01-02   Printer   West   CUST0092         1  883.87   883.87
4  2025-01-17    Tablet  North   CUST0095         3  742.68  2228.04

In [8]:
DataSet.tail()

           Date     Product Region CustomerID  Quantity   Sales  Revenue
500  2025-03-23  Smartphone  South   CUST0007         8  698.42  5587.36
501  2025-03-08      Tablet  South   CUST0074         4  656.06  2624.24
502  2025-02-26     Printer  South   CUST0052         8  472.72  3781.76
503  2025-02-02      Laptop   West   CUST0079         1  104.45   104.45
504  2025-03-30    Keyboard  North   CUST0054         3  722.95  2168.85

In [11]:
DataSet.describe()

         Quantity       Sales      Revenue
count  505.000000  490.000000   490.000000
mean     4.936634  551.856755  2708.478571
std      2.664423  261.823925  2067.350600
min      1.000000  104.450000   104.450000
25%      2.000000  314.157500  1019.580000
50%      5.000000  559.740000  2106.935000
75%      7.000000  763.512500  4010.942500
max      9.000000  999.470000  8995.230000

In [20]:
DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        505 non-null    datetime64[ns]
 1   Product     505 non-null    object
 2   Region      505 non-null    object
 3   CustomerID  505 non-null    object
 4   Quantity    505 non-null    int64
 5   Sales       505 non-null    float64
 6   Revenue     505 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 27.7+ KB

In [17]:
# Handle missing values
DataSet["Sales"] = DataSet["Sales"].fillna(DataSet["Sales"].mean())  # Fill missing values with the mean of the column

DataSet["Revenue"] = DataSet["Revenue"].fillna(DataSet["Revenue"].mean())  # Fill missing values with the mean of the column["Revenue"] = df["Revenue"].fillna(df["Revenue"].mean())  # Fill missing values with the mean of the column

In [18]:
DataSet.isna().sum()

Date          0
Product       0
Region        0
CustomerID    0
Quantity      0
Sales         0
Revenue       0
dtype: int64

In [19]:
# Convert 'Date' column to datetime
DataSet['Date'] = pd.to_datetime(DataSet['Date'])

In [21]:
DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        505 non-null    datetime64[ns]
 1   Product     505 non-null    object
 2   Region      505 non-null    object
 3   CustomerID  505 non-null    object
 4   Quantity    505 non-null    int64
 5   Sales       505 non-null    float64
 6   Revenue     505 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 27.7+ KB

In [22]:
# Extract Month and Year
DataSet['Month'] = DataSet['Date'].dt.month
DataSet['Year'] = DataSet['Date'].dt.year

In [23]:
DataSet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        505 non-null    datetime64[ns]
 1   Product     505 non-null    object
 2   Region      505 non-null    object
 3   CustomerID  505 non-null    object
 4   Quantity    505 non-null    int64
 5   Sales       505 non-null    float64
 6   Revenue     505 non-null    float64
 7   Month       505 non-null    int32
 8   Year        505 non-null    int32
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(3)
memory usage: 31.7+ KB

In [24]:
# Remove duplicates
DataSet.drop_duplicates(inplace=True)

In [25]:
DataSet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        500 non-null    datetime64[ns]
 1   Product     500 non-null    object
 2   Region      500 non-null    object
 3   CustomerID  500 non-null    object
 4   Quantity    500 non-null    int64
 5   Sales       500 non-null    float64
 6   Revenue     500 non-null    float64
 7   Month       500 non-null    int32
 8   Year        500 non-null    int32
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(3)
memory usage: 35.2+ KB

In [29]:
DataSet

,Date,Product,Region,CustomerID,Quantity,Sales,Revenue,Month,Year
0,2025-02-16,Printer,East,CUST0065,8,146.770000,1174.16,2,2025
1,2025-03-28,Monitor,South,CUST0032,3,587.170000,1761.51,3,2025
2,2025-03-27,Keyboard,East,CUST0034,2,738.150000,1476.30,3,2025
3,2025-01-02,Printer,West,CUST0092,1,883.870000,883.87,1,2025
4,2025-01-17,Tablet,North,CUST0095,3,742.680000,2228.04,1,2025
...,...,...,...,...,...,...,...,...,...
495,2025-02-11,Mouse,East,CUST0029,3,551.856755,494.64,2,2025
496,2025-01-16,Laptop,North,CUST0049,6,164.130000,984.78,1,2025
497,2025-01-19,Monitor,North,CUST0045,9,110.900000,998.10,1,2025
498,2025-02-14,Smartphone,West,CUST0093,6,960.850000,5765.10,2,2025
499,2025-02-09,Mouse,South,CUST0030,9,763.760000,6873.84,2,2025

In [30]:
DataSet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        500 non-null    datetime64[ns]
 1   Product     500 non-null    object
 2   Region      500 non-null    object
 3   CustomerID  500 non-null    object
 4   Quantity    500 non-null    int64
 5   Sales       500 non-null    float64
 6   Revenue     500 non-null    float64
 7   Month       500 non-null    int32
 8   Year        500 non-null    int32
dtypes: datetime64[ns](1), float64(2), int32(2), int64(1), object(3)
memory usage: 35.2+ KB

In [31]:
# Summary statistics for numerical columns
summary_stats = DataSet[['Sales', 'Revenue', 'Quantity']].describe()
summary_stats

            Sales      Revenue    Quantity
count  500.000000   500.000000  500.000000
mean   552.066123  2707.030037    4.938000
std    258.148739  2038.426310    2.663145
min    104.450000   104.450000    1.000000
25%    321.575000  1045.642500    2.000000
50%    551.856755  2179.015000    5.000000
75%    760.877500  3895.937500    7.000000
max    999.470000  8995.230000    9.000000